---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-app-config-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/p4ali/argocd-app-config
  password: ${GITHUB_TOKEN}
  username: not-used